name: CI/CD to Azure VMSS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure VMSS using Custom Script Extension
        run: |
          echo "🚀 Triggering VMSS extension update with force-refresh..."
          az vmss extension set \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --vmss-name "${{ secrets.VMSS_NAME }}" \
            --name customScript \
            --publisher Microsoft.Azure.Extensions \
            --version 2.0 \
            --settings '{
              "fileUris": ["${{ secrets.DEPLOY_SCRIPT_URL }}"],
              "commandToExecute": "bash Deploy.sh"
            }' \
            --force-update

      - name: ✅ Verify VMSS deployment status
        run: |
          echo "🔍 Verifying VMSS deployment status..."

          STATUS=$(az vmss list-instances \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --name "${{ secrets.VMSS_NAME }}" \
            --query "[].{Instance:instanceId, Status:instanceView.extensions[?name=='customScript']|[0].statuses[0].code}" \
            --output tsv)

          echo "$STATUS"

          echo "$STATUS" | grep -q "ProvisioningState/succeeded"
          if [ $? -ne 0 ]; then
            echo "❌ One or more VMSS instances failed during customScript execution."
            exit 1
          else
            echo "✅ All VMSS instances reported successful deployment."
          fi
